T#258/access table
NationalSecurityAgency/skills-service pull request #263
Opened 2021-01-04 19:47 UTC by sudo-may

2021-01-04 19:51 UTC, mosefer commented on e2e-tests/cypress/integration/accessibility_specs.js
> +  it.only('project', () => {
remove .only

2021-01-04 19:52 UTC, mosefer requested changes
remove .only from accessibility_specs

2021-01-04 21:05 UTC, sudo-may commented on e2e-tests/cypress/integration/accessibility_specs.js
> +  it.only('project', () => {
removed

2021-01-05 17:26 UTC, mosefer approved these changes

2021-01-05 17:27 UTC, merged