#89 upgraded groovy to 3.0.4, upgraded various other dependencies
NationalSecurityAgency/skills-service pull request #98
Opened 2020-09-10 19:47 UTC by mosefer

2020-09-11 10:57 UTC, sudo-may approved these changes

2020-09-11 11:03 UTC, sudo-may requested changes
please upgrade to the latest groovy compiler 3.8.X and groovy to 3.0.5 version

2020-09-14 18:38 UTC, mosefer commented
3.6.0-03 is the latest version available of groovy-eclipse-compiler: https://bintray.com/groovy/maven/groovy-eclipse-compiler

2020-09-15 16:50 UTC, sudo-may approved these changes

2020-09-21 10:26 UTC, sudo-may commented
merged manually

2020-09-21 10:26 UTC, closed without merging